import React, { createContext, useState, useContext, ReactNode, useCallback } from 'react';

type Locale = 'en' | 'es';

const translations: Record<Locale, Record<string, string>> = {
  en: {
    'header.title': 'Help Desk',
    'header.dashboard': 'Dashboard',
    'header.manageUsers': 'Manage Users',
    'header.settings': 'Settings',
    'header.newTicket': 'New Ticket',
    'header.logout': 'Logout',
    'header.changeAvatar': 'Change Avatar',
    'ticketList.archivedTitle': 'Archived Tickets',
    'ticketList.title': 'All Tickets',
    'ticketList.showArchived': 'Show archived tickets',
    'ticketList.showUnassigned': 'Show unassigned only',
    'ticketList.filterTypes.priority': 'Priority',
    'ticketList.filterTypes.category': 'Category',
    'ticketList.filterTypes.status': 'Status',
    'ticketList.clearFilter': 'Clear',
    'ticketList.noTickets': 'No tickets found.',
    'ticket.archived': 'Archived',
    'ticketDetails.customer': 'Customer',
    'ticketDetails.assignee': 'Assignee',
    'ticketDetails.unassigned': 'Unassigned',
    'ticketDetails.created': 'Created On',
    'ticketDetails.category': 'Category',
    'ticketDetails.priority': 'Priority',
    'ticketDetails.status': 'Status',
    'ticketDetails.description': 'Description',
    'ticketDetails.conversation': 'Conversation',
    'ticketDetails.assignmentHistory': 'Assignment History',
    'ticketDetails.assignedTo': 'Assigned to {agentName}',
    'ticketDetails.unassignedEvent': 'Ticket became unassigned',
    'ticketDetails.noAssignmentHistory': 'No assignment history available.',
    'ticketDetails.noComments': 'No comments yet.',
    'ticketDetails.addCommentPlaceholder': 'Add a comment...',
    'buttons.archive': 'Archive',
    'buttons.unarchive': 'Unarchive',
    'buttons.edit': 'Edit',
    'buttons.cancel': 'Cancel',
    'buttons.saveChanges': 'Save Changes',
    'buttons.addComment': 'Add Comment',
    'buttons.createTicket': 'Create Ticket',
    'newTicketModal.title': 'Create New Ticket',
    'newTicketModal.customerName': "Customer's Name",
    'newTicketModal.subject': 'Subject',
    'newTicketModal.description': 'Description',
    'newTicketModal.category': 'Category',
    'newTicketModal.priority': 'Priority',
    'newTicketModal.suggesting': 'Suggesting...',
    'newTicketModal.aiSuggest': 'AI Suggest',
    'newTicketModal.errorDescription': 'Please enter a description to use AI suggestions.',
    'newTicketModal.errorAISuggest': 'Failed to get suggestions from AI.',
    'newTicketModal.errorRequiredFields': 'Please fill out all required fields.',
    'dashboard.title': 'Dashboard',
    'dashboard.totalTickets': 'Total Tickets',
    'dashboard.openTickets': 'Open',
    'dashboard.inProgressTickets': 'In Progress',
    'dashboard.resolvedTickets': 'Resolved',
    'dashboard.byPriority': 'Tickets by Priority',
    'dashboard.byCategory': 'Tickets by Category',
    'dashboard.noData': 'No data available',
    'roles.Admin': 'Admin',
    'roles.Agent': 'Agent',
    'roles.User': 'User',
    'statuses.Open': 'Open',
    'statuses.In Progress': 'In Progress',
    'statuses.Resolved': 'Resolved',
    'statuses.Closed': 'Closed',
    'priorities.Low': 'Low',
    'priorities.Medium': 'Medium',
    'priorities.High': 'High',
    'priorities.Critical': 'Critical',
    'categories.Hardware': 'Hardware',
    'categories.Software': 'Software',
    'categories.Network': 'Network',
    'categories.Account': 'Account',
    'categories.Other': 'Other',
    'login.title': 'Sign in to your account',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign in',
    'login.error': 'Invalid credentials. Please try again.',
    'users.title': 'User Management',
    'users.addUser': 'Add User',
    'users.name': 'Name',
    'users.role': 'Role',
    'users.actions': 'Actions',
    'users.resetPin': 'Reset PIN',
    'users.delete': 'Delete',
    'users.confirmDelete': 'Are you sure you want to permanently delete this user? This action cannot be undone.',
    'users.showInactive': 'Show inactive users',
    'users.inactive': 'Inactive',
    'users.deactivate': 'Deactivate',
    'users.reactivate': 'Reactivate',
    'users.deleteUserTitle': 'Delete User',
    'userModal.createUserTitle': 'Create New User',
    'userModal.resetPinTitle': 'Reset PIN for',
    'userModal.nameLabel': 'Full Name',
    'userModal.usernameLabel': 'Username',
    'userModal.roleLabel': 'Role',
    'userModal.pinLabel': 'New 4-Digit PIN',
    'userModal.saveUser': 'Save User',
    'userModal.updatePin': 'Update PIN',
    'userModal.errorPinFormat': 'PIN must be 4 digits.',
    'userModal.errorRequired': 'This field is required.',
    'branding.title': 'Branding Settings',
    'branding.companyName': 'Company Name',
    'branding.companyNamePlaceholder': 'Enter your company name',
    'branding.logoUrl': 'Logo URL',
    'branding.logoUrlPlaceholder': 'https://example.com/logo.png',
    'branding.faviconUrl': 'Favicon URL',
    'branding.faviconUrlPlaceholder': 'https://example.com/favicon.ico',
    'branding.logoPreview': 'Logo Preview',
    'branding.save': 'Save Branding',
  },
  es: {
    'header.title': 'Mesa de Ayuda',
    'header.dashboard': 'Panel',
    'header.manageUsers': 'Administrar Usuarios',
    'header.settings': 'Ajustes',
    'header.newTicket': 'Nuevo Ticket',
    'header.logout': 'Cerrar Sesión',
    'header.changeAvatar': 'Cambiar Avatar',
    'ticketList.archivedTitle': 'Tickets Archivados',
    'ticketList.title': 'Todos los Tickets',
    'ticketList.showArchived': 'Mostrar tickets archivados',
    'ticketList.showUnassigned': 'Mostrar solo sin asignar',
    'ticketList.filterTypes.priority': 'Prioridad',
    'ticketList.filterTypes.category': 'Categoría',
    'ticketList.filterTypes.status': 'Estado',
    'ticketList.clearFilter': 'Limpiar',
    'ticketList.noTickets': 'No se encontraron tickets.',
    'ticket.archived': 'Archivado',
    'ticketDetails.customer': 'Cliente',
    'ticketDetails.assignee': 'Asignado a',
    'ticketDetails.unassigned': 'Sin asignar',
    'ticketDetails.created': 'Creado el',
    'ticketDetails.category': 'Categoría',
    'ticketDetails.priority': 'Prioridad',
    'ticketDetails.status': 'Estado',
    'ticketDetails.description': 'Descripción',
    'ticketDetails.conversation': 'Conversación',
    'ticketDetails.assignmentHistory': 'Historial de Asignación',
    'ticketDetails.assignedTo': 'Asignado a {agentName}',
    'ticketDetails.unassignedEvent': 'El ticket quedó sin asignar',
    'ticketDetails.noAssignmentHistory': 'No hay historial de asignación disponible.',
    'ticketDetails.noComments': 'Aún no hay comentarios.',
    'ticketDetails.addCommentPlaceholder': 'Añadir un comentario...',
    'buttons.archive': 'Archivar',
    'buttons.unarchive': 'Desarchivar',
    'buttons.edit': 'Editar',
    'buttons.cancel': 'Cancelar',
    'buttons.saveChanges': 'Guardar Cambios',
    'buttons.addComment': 'Añadir Comentario',
    'buttons.createTicket': 'Crear Ticket',
    'newTicketModal.title': 'Crear Nuevo Ticket',
    'newTicketModal.customerName': 'Nombre del Cliente',
    'newTicketModal.subject': 'Asunto',
    'newTicketModal.description': 'Descripción',
    'newTicketModal.category': 'Categoría',
    'newTicketModal.priority': 'Prioridad',
    'newTicketModal.suggesting': 'Sugiriendo...',
    'newTicketModal.aiSuggest': 'Sugerencia de IA',
    'newTicketModal.errorDescription': 'Por favor ingrese una descripción para usar las sugerencias de IA.',
    'newTicketModal.errorAISuggest': 'Error al obtener sugerencias de la IA.',
    'newTicketModal.errorRequiredFields': 'Por favor, rellene todos los campos obligatorios.',
    'dashboard.title': 'Panel',
    'dashboard.totalTickets': 'Tickets Totales',
    'dashboard.openTickets': 'Abiertos',
    'dashboard.inProgressTickets': 'En Progreso',
    'dashboard.resolvedTickets': 'Resueltos',
    'dashboard.byPriority': 'Tickets por Prioridad',
    'dashboard.byCategory': 'Tickets por Categoría',
    'dashboard.noData': 'No hay datos disponibles',
    'roles.Admin': 'Administrador',
    'roles.Agent': 'Agente',
    'roles.User': 'Usuario',
    'statuses.Open': 'Abierto',
    'statuses.In Progress': 'En Progreso',
    'statuses.Resolved': 'Resuelto',
    'statuses.Closed': 'Cerrado',
    'priorities.Low': 'Baja',
    'priorities.Medium': 'Media',
    'priorities.High': 'Alta',
    'priorities.Critical': 'Crítica',
    'categories.Hardware': 'Hardware',
    'categories.Software': 'Software',
    'categories.Network': 'Red',
    'categories.Account': 'Cuenta',
    'categories.Other': 'Otro',
    'login.title': 'Inicia sesión en tu cuenta',
    'login.username': 'Nombre de usuario',
    'login.password': 'Contraseña',
    'login.signIn': 'Iniciar Sesión',
    'login.error': 'Credenciales inválidas. Por favor, inténtelo de nuevo.',
    'users.title': 'Gestión de Usuarios',
    'users.addUser': 'Añadir Usuario',
    'users.name': 'Nombre',
    'users.role': 'Rol',
    'users.actions': 'Acciones',
    'users.resetPin': 'Restablecer PIN',
    'users.delete': 'Eliminar',
    'users.confirmDelete': '¿Estás seguro de que quieres eliminar permanentemente a este usuario? Esta acción no se puede deshacer.',
    'users.showInactive': 'Mostrar usuarios inactivos',
    'users.inactive': 'Inactivo',
    'users.deactivate': 'Desactivar',
    'users.reactivate': 'Reactivar',
    'users.deleteUserTitle': 'Eliminar Usuario',
    'userModal.createUserTitle': 'Crear Nuevo Usuario',
    'userModal.resetPinTitle': 'Restablecer PIN para',
    'userModal.nameLabel': 'Nombre Completo',
    'userModal.usernameLabel': 'Nombre de Usuario',
    'userModal.roleLabel': 'Rol',
    'userModal.pinLabel': 'Nuevo PIN de 4 dígitos',
    'userModal.saveUser': 'Guardar Usuario',
    'userModal.updatePin': 'Actualizar PIN',
    'userModal.errorPinFormat': 'El PIN debe tener 4 dígitos.',
    'userModal.errorRequired': 'Este campo es obligatorio.',
    'branding.title': 'Ajustes de Marca',
    'branding.companyName': 'Nombre de la Empresa',
    'branding.companyNamePlaceholder': 'Ingrese el nombre de su empresa',
    'branding.logoUrl': 'URL del Logo',
    'branding.logoUrlPlaceholder': 'https://ejemplo.com/logo.png',
    'branding.faviconUrl': 'URL del Favicon',
    'branding.faviconUrlPlaceholder': 'https://ejemplo.com/favicon.ico',
    'branding.logoPreview': 'Vista Previa del Logo',
    'branding.save': 'Guardar Marca',
  }
};


interface LocalizationContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, fallback?: string) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocale] = useState<Locale>('en');

  const t = useCallback((key: string, fallback?: string): string => {
    return translations[locale][key] || translations['en'][key] || fallback || key;
  }, [locale]);

  const contextValue = {
    locale,
    setLocale,
    t,
  };

  return (
    <LocalizationContext.Provider value={contextValue}>
      {children}
    {/* FIX: Corrected typo in closing tag from Localization-Provider to LocalizationContext.Provider */}
    </LocalizationContext.Provider>
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (context === undefined) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};